Feature/fetch one project page
SoftRyzen-internship/vesta_main_site pull request #92
Opened 2024-06-13 14:28 UTC by Samokhvalova-Nata

2024-06-13 20:17 UTC, Ljuzifer commented on src/sections/pageProjects/ProjectTemplate/ProjectTemplate.tsx
>            <div className='mb-[30px]  md:mb-10 md:max-w-[492px] xl:mb-0'>
тут контейнер має бути

2024-06-13 20:17 UTC, Ljuzifer commented on src/app/projects/[slug]/page.tsx
>        <b>{slug}</b>
а це чого не видалила?)

2024-06-13 20:19 UTC, Ljuzifer commented on src/sections/pageProjects/ProjectTemplate/ProjectTemplate.type.ts
> +  id: string | number;
там же string

2024-06-13 20:20 UTC, Ljuzifer requested changes
і онови дев бо змінив next.config

2024-06-14 07:00 UTC, Samokhvalova-Nata commented on src/sections/pageProjects/ProjectTemplate/ProjectTemplate.tsx
>            <div className='mb-[30px]  md:mb-10 md:max-w-[492px] xl:mb-0'>
Нащо? він вище, у div одразу після section

2024-06-14 07:02 UTC, Samokhvalova-Nata commented on src/app/projects/[slug]/page.tsx
>        <b>{slug}</b>
навіщо це видаляти?)

2024-06-14 07:02 UTC, Samokhvalova-Nata commented on src/sections/pageProjects/ProjectTemplate/ProjectTemplate.type.ts
> +  id: string | number;
++

2024-06-14 10:32 UTC, Ljuzifer commented on src/app/projects/[slug]/page.tsx
>        <b>{slug}</b>
це я коли перевіряв прописував <b>{slug}</b>, навіщо воно тут?))

2024-06-15 16:06 UTC, Ljuzifer approved these changes

2024-06-15 16:07 UTC, merged